"""empty message

Revision ID: 74263e03d5a9
Revises: 7d7a93a00222
Create Date: 2024-08-30 13:00:01.937277

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74263e03d5a9'
down_revision = '7d7a93a00222'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_pictures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('picture_url', sa.String(), nullable=False),
    sa.Column('uploaded_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('profile_picture_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_picture_url', sa.TEXT(), nullable=True))

    op.drop_table('user_pictures')
    # ### end Alembic commands ###
